# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Notes
    identifier: tags
    weight: 20
  - name: Machine Learning
    parent: tags
    url: /machine-learning/
    weight: 11
  - name: 数据结构
    parent: tags
    url: https://wangyiou-notebook.netlify.app/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84/
    weight: 12
